name: Run WebdriverIO Tests Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Scraping Futebol
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run WebdriverIO tests
        run: npx wdio wdio.conf.ts
